# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=50, verbose_name='\u9009\u9879')),
                ('iscorrect', models.BooleanField(verbose_name='\u662f\u5426\u6b63\u786e\u7b54\u6848')),
            ],
            options={
                'verbose_name': '\u95ee\u9898\u9009\u9879',
                'verbose_name_plural': '\u95ee\u9898\u9009\u9879',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=50, verbose_name='\u73a9\u5bb6')),
                ('player_password', models.CharField(max_length=50, verbose_name='\u5bc6\u7801')),
                ('player_score', models.IntegerField(default=0, verbose_name='\u5f97\u5206')),
                ('rank', models.IntegerField(default=0, verbose_name='\u6392\u540d')),
                ('role', models.CharField(choices=[('S', '\u521b\u5efa\u8005'), ('C', '\u53c2\u4e0e\u8005'), ('A', '\u521b\u5efa\u8005\u548c\u53c2\u4e0e\u8005')], default='C', max_length=20, verbose_name='\u89d2\u8272')),
            ],
            options={
                'verbose_name': '\u73a9\u5bb6',
                'verbose_name_plural': '\u73a9\u5bb6',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=100, verbose_name='\u95ee\u9898')),
                ('question_category', models.CharField(choices=[('EJ', '\u5a31\u4e50'), ('LF', '\u751f\u6d3b'), ('HI', '\u5386\u53f2'), ('EC', '\u7ecf\u6d4e'), ('PO', '\u653f\u6cbb'), ('CU', '\u6587\u5316'), ('PH', '\u7269\u7406'), ('CH', '\u5316\u5b66'), ('BI', '\u751f\u7269'), ('IT', '\u6280\u672f'), ('OT', '\u5176\u5b83')], default='OT', max_length=20, verbose_name='\u5206\u7c7b')),
                ('question_score', models.IntegerField(verbose_name='\u5206\u503c')),
                ('question_level', models.CharField(choices=[('ES', '\u5bb9\u6613'), ('NM', '\u666e\u901a'), ('HD', '\u56f0\u96be')], default='ES', max_length=20, verbose_name='\u96be\u5ea6')),
                ('question_limit_second', models.IntegerField(verbose_name='\u9650\u65f6/\u79d2')),
                ('question_create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u95ee\u9898',
                'verbose_name_plural': '\u95ee\u9898',
            },
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('player_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.Player')),
                ('answer_count', models.IntegerField(default=0, verbose_name='\u56de\u7b54\u603b\u6570')),
                ('success_count', models.IntegerField(default=0, verbose_name='\u56de\u7b54\u6b63\u786e\u6570')),
                ('fail_count', models.IntegerField(default=0, verbose_name='\u56de\u7b54\u9519\u8bef\u6570')),
            ],
            bases=('quiz.player',),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('player_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.Player')),
                ('create_count', models.IntegerField(default=0, verbose_name='\u95ee\u9898\u521b\u5efa\u6570')),
            ],
            bases=('quiz.player',),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_creater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Supplier', verbose_name='\u521b\u5efa\u8005'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_solver',
            field=models.ManyToManyField(to='quiz.Consumer', verbose_name='\u53c2\u4e0e\u8005'),
        ),
    ]
