# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumer',
            options={'verbose_name': '\u95ee\u9898\u53c2\u4e0e\u8005', 'verbose_name_plural': '\u95ee\u9898\u53c2\u4e0e\u8005'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': '\u95ee\u9898\u521b\u5efa\u8005', 'verbose_name_plural': '\u95ee\u9898\u521b\u5efa\u8005'},
        ),
        migrations.AlterField(
            model_name='player',
            name='player_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='\u73a9\u5bb6'),
        ),
    ]
