# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 08:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20151227_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='\u73a9\u5bb6\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_level',
            field=models.CharField(max_length=4, verbose_name='\u96be\u5ea6'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_limit_second',
            field=models.IntegerField(default=20, verbose_name='\u9650\u65f6/\u79d2'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_score',
            field=models.IntegerField(help_text='\u5206\u503c\u57280~100\u4e4b\u95f4', validators=[django.core.validators.MaxValueValidator(100, '\u8d85\u51fa\u6700\u5927\u503c 100'), django.core.validators.MinValueValidator(0, '\u8d85\u51fa\u6700\u5c0f\u503c 0')], verbose_name='\u5206\u503c'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_solver',
            field=models.ManyToManyField(blank=True, to='quiz.Consumer', verbose_name='\u53c2\u4e0e\u8005'),
        ),
    ]
