# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20151228_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': '\u95ee\u9898\u5e93', 'verbose_name_plural': '\u95ee\u9898\u5e93'},
        ),
        migrations.AddField(
            model_name='question',
            name='question_close_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u5173\u95ed\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_level',
            field=models.CharField(default='\u5bb9\u6613', max_length=4, verbose_name='\u96be\u5ea6'),
        ),
    ]
