# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 01:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20151229_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_level',
            field=models.CharField(blank=True, max_length=4, verbose_name='\u96be\u5ea6'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_close_at',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 29, 17, 52, 48, 838650), verbose_name='\u5173\u95ed\u65f6\u95f4'),
        ),
    ]
