# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 06:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20151229_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='_question_level',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_close_at',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 29, 22, 44, 26, 917801), verbose_name='\u5173\u95ed\u65f6\u95f4'),
        ),
    ]
